### ISSUE TITLE
Minified version not working

### ISSUE THREAD

**Issue by jonasch** [ejmarino/angular-ms#1]
Hey, i tried to use your library for a service and noticed, that the minified version is not running.
When I try to inject the ngmsMessageService, I get this error:

Error: [$injector:unpr] Unknown provider: eProvider <- e <- ngmsMessageService

This is not only happening in my project, also in the demo project in your github repository. I guess there is something wrong with the minification. I did not study your code, but I think it can be fixed by a solution like this:
http://thegreenpizza.github.io/2013/05/25/building-minification-safe-angular.js-applications/

Pls test it in your example project before you ask me to provide a plunkr, it is much easier to check locally ;)

Best,
Jonas

**Comment by ejmarino** [comment]
Thanks for your comment. I will check it.

**Comment by ejmarino** [comment]
@jonasch: It is fixed. Test and demo are working. If you have a problem let me now. Thanks.

**Comment by jonasch** [comment]
Works like a charm ;)
Thanks and keep up the good work!
